### ISSUE TITLE
MAJOR ISSUE with minimization due to missing 'semi-colon' !!!! please add

### ISSUE THREAD

**Issue by JoelParke** [mishguruorg/angular-timezone-selector#45]
After **several days** and scratching my head.  I discovered that angular-timezone-selector.js does not end with a ';' which causes no issues with the code.  However in my **yeoman angular-fullstack** project, when the code is minimized, this causes the minimized code to fail with:

```
Uncaught TypeError: angular.module(...).constant(...).constant(...).factory(...).factory(...).factory(...).directive(...) is not a function
```

**PLEASE add this SEMI_COLON to save other many hours!**

Thanks much!

**Comment by tkarls** [comment]
OMG. Thanks. I spent the entire afternoon debugging my angular app and finally found this!

Too bad project lead does not merge #49 or provide some other fix.

**Comment by ashokfernandez** [comment]
Closing as this seems to be more an issue with your build system than the project itself.

**Comment by tkarls** [comment]
I kinda disagree that this is only a build system issue.

As per best practice the bower file should point out non-minified code (which you do!) and then each project is supposed to minify the code themselves.  Atleast this is how I have understood things.

Then, I think the various packages must provide code that can be minified by popular minification tools without causing errors.

For instance I would consider a package to have an error if the dependencies was not annotated (yours are!) etc.

In this situation, all that is  needed is a small semicolon. This is how I patched it. Quick and dirty to get it to work in my setup.

https://github.com/tkarls/angular-timezone-selector/commit/2d71257ff5e94f983d02d15445415cc5942e7473

However, I realize that the dist/ version is generated by your build system. I have not looked into it but I can imagine it would be pretty easy to end up with that last little semicolon.

**Comment by JoelParke** [comment]
I too modified the code so that it has that semicolon. The original code didn't have one and without it, the standard packages that minimize the code, cause the minimized code to break.  I reported this as an issue to the minimizer and they felt since this is almost the only package/code that creates this issue, it was better to just fix the package source.  Since the semicolon is optional in javascript, but very helpful in this case, please just add the semicolon to your project. (unless you have already done that fix :-))
Thanks!  This will save others time! And it has no affect on your code directly!
